services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    environment:
      - PORT=8000
      - HOSTNAME=0.0.0.0
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/bi-chatbot?sslmode=disable
      - AUTH_TRUST_HOST=true
      - AUTH_URL=http://localhost:3000/api/auth
    depends_on:
      - postgres
